import { Subject, Question, Badge } from './types';

export const INITIAL_SUBJECTS: Subject[] = [
  { id: 'nt', name: 'Nguyên tử', icon: 'Atom', description: 'Cấu tạo nguyên tử, phân lớp electron, hạt nhân.', questionsCount: 7, level: 1 },
  { id: 'nthh', name: 'Nguyên tố hóa học', icon: 'Box', description: 'Bảng tuần hoàn, kí hiệu, chu kì và nhóm.', questionsCount: 8, level: 2 },
  { id: 'hh', name: 'Hợp chất vô cơ', icon: 'FlaskConical', description: 'Oxide, Acid, Base, Muối.', questionsCount: 9, level: 3 },
  { id: 'kl', name: 'Kim loại', icon: 'Hammer', description: 'Tính chất, dãy hoạt động hóa học.', questionsCount: 8, level: 4 },
  { id: 'pkr', name: 'Phi kim', icon: 'CloudRain', description: 'Chlorine, Carbon, Silicon.', questionsCount: 7, level: 5 },
  { id: 'hc', name: 'Hợp chất hữu cơ', icon: 'Leaf', description: 'Methane, Ethylene, Acetylene, Ethanol, Acetic acid.', questionsCount: 13, level: 6 },
];

export const INITIAL_QUESTIONS: Question[] = [
  // --- NGUYÊN TỬ (nt) ---
  { id: 'qnt_1', subjectId: 'nt', content: 'Nguyên tử gồm những loại hạt cơ bản nào?', type: 'multiple-choice', options: ['Proton, Neutron, Electron', 'Proton, Neutron', 'Proton, Electron', 'Neutron, Electron'], correctAnswer: 'Proton, Neutron, Electron', explanation: 'Nguyên tử bao gồm hạt nhân (gồm Proton, Neutron) và lớp vỏ (Electron).', difficulty: 'easy' },
  { id: 'qnt_2', subjectId: 'nt', content: 'Hạt nào mang điện tích dương trong nguyên tử?', type: 'multiple-choice', options: ['Electron', 'Neutron', 'Proton', 'Hạt nhân'], correctAnswer: 'Proton', explanation: 'Proton mang điện tích (+), Electron mang điện (-), Neutron không mang điện.', difficulty: 'easy' },
  { id: 'qnt_3', subjectId: 'nt', content: 'Lớp vỏ nguyên tử được cấu tạo từ loại hạt nào?', type: 'multiple-choice', options: ['Proton', 'Neutron', 'Electron', 'Hạt nhân'], correctAnswer: 'Electron', explanation: 'Lớp vỏ tạo nên từ các hạt electron.', difficulty: 'easy' },
  { id: 'qnt_4', subjectId: 'nt', content: 'Khối lượng nguyên tử phân bố như thế nào?', type: 'multiple-choice', options: ['Tập trung hết ở vỏ', 'Tập trung chủ yếu ở hạt nhân', 'Phân chia đều', 'Không xác định được'], correctAnswer: 'Tập trung chủ yếu ở hạt nhân', explanation: 'Khối lượng proton và neutron rất lớn so với electron nên khối lượng nguyên tử hầu hết tập trung ở hạt nhân.', difficulty: 'medium' },
  { id: 'qnt_5', subjectId: 'nt', content: 'Số khối (Ký hiệu: A) đặc trưng bằng tổng số hạt nào?', type: 'multiple-choice', options: ['Proton', 'Proton và Neutron', 'Neutron', 'Electron và Proton'], correctAnswer: 'Proton và Neutron', explanation: 'A = Z (proton) + N (neutron).', difficulty: 'medium' },
  { id: 'qnt_6', subjectId: 'nt', content: 'Đồng vị là các nguyên tử có cùng hạt gì nhưng khác hạt gì?', type: 'multiple-choice', options: ['Cùng P, khác N', 'Cùng P, khác E', 'Cùng N, khác P', 'Cùng E, khác N'], correctAnswer: 'Cùng P, khác N', explanation: 'Đồng vị là những nguyên tử của cùng một nguyên tố, cùng điện tích hạt nhân (Z/Proton) nhưng khác số neutron N.', difficulty: 'hard' },
  { id: 'qnt_7', subjectId: 'nt', content: 'Nguyên tử trung hòa về điện là do?', type: 'multiple-choice', options: ['Số P = số N', 'Số P = số E', 'Số N = số E', 'Chỉ có P và N'], correctAnswer: 'Số P = số E', explanation: 'Vì điện tích của P và E bằng nhau về độ lớn nhưng trái dấu, nên khi số lượng bằng nhau thì nguyên tử trung hòa về điện.', difficulty: 'easy' },

  // --- NGUYÊN TỐ HÓA HỌC (nthh) ---
  { id: 'qn_1', subjectId: 'nthh', content: 'Nguyên tố hóa học là tập hợp các nguyên tử có cùng đặc điểm gì?', type: 'multiple-choice', options: ['Số proton', 'Số neutron', 'Lớp vỏ', 'Số electron phân lớp ngoài'], correctAnswer: 'Số proton', explanation: 'Nguyên tố hóa học là tập hợp những nguyên tử cùng loại, có cùng số proton trong hạt nhân.', difficulty: 'easy' },
  { id: 'qn_2', subjectId: 'nthh', content: 'Bảng tuần hoàn các nguyên tố hóa học được sắp xếp theo nguyên tắc nào?', type: 'multiple-choice', options: ['Điện tích hạt nhân tăng dần', 'Khối lượng nguyên tử tăng', 'Khối lượng riêng', 'Phi vần A, B, C'], correctAnswer: 'Điện tích hạt nhân tăng dần', explanation: 'Các nguyên tố được xếp theo chiều tăng dần của điện tích hạt nhân nguyên tử (số proton/Z).', difficulty: 'easy' },
  { id: 'qn_3', subjectId: 'nthh', content: 'Kí hiệu hóa học của nguyên tố Calcium (Canxi) là gì?', type: 'multiple-choice', options: ['Ca', 'C', 'Co', 'Cu'], correctAnswer: 'Ca', explanation: 'Ca là kí hiệu của Calcium. C (Carbon), Cu (Copper).', difficulty: 'easy' },
  { id: 'qn_4', subjectId: 'nthh', content: 'Nguyên tố phổ biến nhất trong vỏ Trái Đất là gì?', type: 'multiple-choice', options: ['Oxygen', 'Iron (Sắt)', 'Silicon', 'Aluminum (Nhôm)'], correctAnswer: 'Oxygen', explanation: 'Oxygen (O) chiếm gần 46.6% khối lượng vỏ Trái Đất.', difficulty: 'medium' },
  { id: 'qn_5', subjectId: 'nthh', content: 'Trong bảng tuần hoàn, các hàng ngang được gọi là gì?', type: 'multiple-choice', options: ['Chu kì', 'Nhóm', 'Ô nguyên tố', 'Cột chính'], correctAnswer: 'Chu kì', explanation: 'Hàng ngang là Chu kì (cùng số lớp electron), Cột dọc là Nhóm.', difficulty: 'medium' },
  { id: 'qn_6', subjectId: 'nthh', content: 'Các nguyên tố nằm ở cùng một Nhóm (cột dọc) Bảng tuần hoàn thường có đặc điểm gì chung?', type: 'multiple-choice', options: ['Tính chất hóa học tương tự nhau', 'Có cùng số electron', 'Có cùng số proton', 'Cùng trạng thái rắn'], correctAnswer: 'Tính chất hóa học tương tự nhau', explanation: 'Các nguyên tố cùng Nhóm thường có số electron lớp ngoài cùng giống nhau nên tính chất hóa học rất tương đồng.', difficulty: 'hard' },
  { id: 'qn_7', subjectId: 'nthh', content: 'Nguyên tố X ở chu kì 3, nhóm IIA. X có bao nhiêu lớp electron?', type: 'multiple-choice', options: ['2', '3', '4', '5'], correctAnswer: '3', explanation: 'Số chu kì bằng chính số lớp electron của nguyên tử.', difficulty: 'medium' },
  { id: 'qn_8', subjectId: 'nthh', content: 'Kí hiệu hóa học của nguyên tố Neon là gì?', type: 'multiple-choice', options: ['N', 'Ne', 'Na', 'Ni'], correctAnswer: 'Ne', explanation: 'Ne là Neon, N là Nitrogen, Na là Sodium, Ni là Nickel.', difficulty: 'easy' },

  // --- HỢP CHẤT VÔ CƠ (hh) ---
  { id: 'qhh_1', subjectId: 'hh', content: 'Acid làm quỳ tím chuyển sang màu gì?', type: 'multiple-choice', options: ['Xanh lục', 'Đỏ', 'Vàng', 'Không đổi màu'], correctAnswer: 'Đỏ', explanation: 'Dung dịch acid làm quỳ tím hóa đỏ.', difficulty: 'easy' },
  { id: 'qhh_2', subjectId: 'hh', content: 'Base tan (kiềm) làm quỳ tím chuyển sang màu gì?', type: 'multiple-choice', options: ['Đỏ', 'Xanh', 'Tím', 'Không màu'], correctAnswer: 'Xanh', explanation: 'Dung dịch kiềm làm quỳ tím hóa xanh.', difficulty: 'easy' },
  { id: 'qhh_3', subjectId: 'hh', content: 'Dung dịch Phenolphthalein chuyển sang màu gì trong môi trường Base?', type: 'multiple-choice', options: ['Hồng', 'Xanh', 'Vàng', 'Đỏ'], correctAnswer: 'Hồng', explanation: 'Phenolphthalein không màu chuyển thành đỏ hồng trong môi trường base.', difficulty: 'easy' },
  { id: 'qhh_4', subjectId: 'hh', content: 'Phản ứng giữa acid và base gọi là phản ứng gì?', type: 'multiple-choice', options: ['Oxi hóa khử', 'Thế', 'Trung hòa', 'Cộng'], correctAnswer: 'Trung hòa', explanation: 'Phản ứng trung hòa luôn tạo ra Muối và Nước.', difficulty: 'medium' },
  { id: 'qhh_5', subjectId: 'hh', content: 'Lưu huỳnh dioxide (SO₂) thuộc loại hợp chất nào?', type: 'multiple-choice', options: ['Oxide base', 'Oxide lưỡng tính', 'Oxide trung tính', 'Oxide acid'], correctAnswer: 'Oxide acid', explanation: 'SO₂ là oxide phi kim tác dụng với nước tạo thành acid H₂SO₃ (Acid sulfurơ).', difficulty: 'medium' },
  { id: 'qhh_6', subjectId: 'hh', content: 'Tên của phân bón Amoni nitrat thường tạo ra từ base và acid nào?', type: 'multiple-choice', options: ['NH3 và HNO3', 'K2O và H2SO4', 'NaOH và HNO3', 'Ca(OH)2 và HCl'], correctAnswer: 'NH3 và HNO3', explanation: 'NH3 tác dụng với HNO3 tạo ra NH4NO3.', difficulty: 'medium' },
  { id: 'qhh_7', subjectId: 'hh', content: 'Nhiệt phân hoàn toàn CaCO₃ (Đá vôi) thu được chất khí nào?', type: 'multiple-choice', options: ['CO₂', 'O₂', 'H₂', 'CO'], correctAnswer: 'CO₂', explanation: 'CaCO3 -> CaO + CO2.', difficulty: 'hard' },
  { id: 'qhh_8', subjectId: 'hh', content: 'Hợp chất nào sau đây là Base không tan?', type: 'multiple-choice', options: ['NaOH', 'KOH', 'Cu(OH)2', 'Ba(OH)2'], correctAnswer: 'Cu(OH)2', explanation: 'Sodium hydroxide (NaOH), Potassium hydroxide (KOH) và Barium hydroxide (Ba(OH)2) là các base tan (kiềm).', difficulty: 'medium' },
  { id: 'qhh_9', subjectId: 'hh', content: 'Dung dịch acid nào có khả năng hòa tan được kim loại Copper (Cu)?', type: 'multiple-choice', options: ['HCl loãng', 'H2SO4 loãng', 'HNO3 đặc', 'H3PO4'], correctAnswer: 'HNO3 đặc', explanation: 'HNO3 là acid có tính oxi hóa mạnh, hòa tan được hầu hết kim loại trừ Au, Pt.', difficulty: 'hard' },

  // --- KIM LOẠI (kl) ---
  { id: 'qkl_1', subjectId: 'kl', content: 'Kim loại nào ở trạng thái lỏng ở điều kiện thường?', type: 'multiple-choice', options: ['Đồng', 'Thủy ngân', 'Sắt', 'Nhôm'], correctAnswer: 'Thủy ngân', explanation: 'Thủy ngân (Hg) là kim loại cực kì đặc biệt duy nhất tồn tại ở thể lỏng.', difficulty: 'easy' },
  { id: 'qkl_2', subjectId: 'kl', content: 'Bởi đặc tính nào người ta làm lõi dây điện bằng Đồng (Cu)?', type: 'multiple-choice', options: ['Tính dẻo', 'Tính ánh kim', 'Dẫn điện tốt giá hợp lý', 'Kim loại nhẹ'], correctAnswer: 'Dẫn điện tốt giá hợp lý', explanation: 'Dù Bạc dẫn điện tốt hơn nhưng Đồng có khả năng dẫn điện cực cao với giá thành rất tốt.', difficulty: 'easy' },
  { id: 'qkl_3', subjectId: 'kl', content: 'Kim loại nào được coi là nhẹ nhất?', type: 'multiple-choice', options: ['Liti', 'Nhôm', 'Magie', 'Natri'], correctAnswer: 'Liti', explanation: 'Liti (Li) là kim loại có khối lượng riêng nhỏ nhất.', difficulty: 'medium' },
  { id: 'qkl_4', subjectId: 'kl', content: 'Dãy hoạt động hóa học của kim loại nào sau đây đúng?', type: 'multiple-choice', options: ['K, Na, Mg, Al, Zn, Fe, Cu, Ag', 'K, Na, Al, Mg, Zn, Fe, Cu, Ag', 'Al, Fe, Zn, Cu, Ag', 'Mg, K, Na, Fe, Zn, Cu, Ag'], correctAnswer: 'K, Na, Mg, Al, Zn, Fe, Cu, Ag', explanation: 'Mẹo nhớ (Khi Nào May Áo Giáp Sắt, Nhìn Sang Đầu Hàng Á Phi Âu).', difficulty: 'medium' },
  { id: 'qkl_5', subjectId: 'kl', content: 'Loại kim loại nào phổ biến là mềm, có thể dễ dàng cắt được bằng dao?', type: 'multiple-choice', options: ['Nhôm', 'Sắt', 'Đồng', 'Natri'], correctAnswer: 'Natri', explanation: 'Các kim loại kiềm như Natri (Na) hay Kali rất mềm.', difficulty: 'medium' },
  { id: 'qkl_6', subjectId: 'kl', content: 'Sắt (Fe) bị "thụ động hóa" trong dung dịch acid nào đặc, nguội?', type: 'multiple-choice', options: ['HCl đặc', 'H2SO4 loãng', 'H2CO3', 'HNO3 đặc nguội'], correctAnswer: 'HNO3 đặc nguội', explanation: 'Fe, Al, Cr bị thụ động hóa (không tác dụng) trong HNO3 đặc nguội và H2SO4 đặc nguội.', difficulty: 'hard' },
  { id: 'qkl_7', subjectId: 'kl', content: 'Thành phần chính của Gang và Thép là nguyên tố nào?', type: 'multiple-choice', options: ['Al và Cu', 'Fe và C', 'Fe và Cu', 'Zn và S'], correctAnswer: 'Fe và C', explanation: 'Gang và thép là hợp kim của Sắt với Carbon và một số nguyên tố khác.', difficulty: 'easy' },
  { id: 'qkl_8', subjectId: 'kl', content: 'Để bảo vệ vỏ tàu thủy bằng thép, người ta thường gắn vào vỏ tàu khối kim loại nào?', type: 'multiple-choice', options: ['Đồng (Cu)', 'Bạc (Ag)', 'Kẽm (Zn)', 'Chì (Pb)'], correctAnswer: 'Kẽm (Zn)', explanation: 'Dùng phương pháp bảo vệ điện hóa, Zn hoạt động hơn Fe nên bị ăn mòn thay cho Fe.', difficulty: 'hard' },

  // --- PHI KIM (pkr) ---
  { id: 'qpkr_1', subjectId: 'pkr', content: 'Phi kim nào là thành phần chính của than đá, kim cương?', type: 'multiple-choice', options: ['Lưu huỳnh', 'Carbon', 'Phosphorus', 'Nitrogen'], correctAnswer: 'Carbon', explanation: 'Kim cương và than chì là các dạng thù hình của Carbon nguyên chất.', difficulty: 'easy' },
  { id: 'qpkr_2', subjectId: 'pkr', content: 'Khí nào chiếm tỷ lệ thể tích cực lớn nhất trong không khí?', type: 'multiple-choice', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correctAnswer: 'Nitrogen', explanation: 'Nitrogen (N₂) chiếm khoảng 78% thể tích không khí (O2 chỉ 21%).', difficulty: 'easy' },
  { id: 'qpkr_3', subjectId: 'pkr', content: 'Lưu huỳnh (Sulfur) ở điều kiện thường có màu gì?', type: 'multiple-choice', options: ['Không màu', 'Xanh lam', 'Vàng chanh', 'Đỏ tươi'], correctAnswer: 'Vàng chanh', explanation: 'Lưu huỳnh (S) là chất rắn, màu vàng chanh nhạt tự nhiên không tan trong nước.', difficulty: 'medium' },
  { id: 'qpkr_4', subjectId: 'pkr', content: 'Nhỏ nước Chlorine (Cl₂) vào dung dịch quỳ tím có hiện tượng gì đặc biệt?', type: 'multiple-choice', options: ['Chỉ hóa đỏ', 'Hóa đỏ rồi mất màu ngay', 'Không đổi màu', 'Hóa xanh'], correctAnswer: 'Hóa đỏ rồi mất màu ngay', explanation: 'Nước Clo chứa HCl (hóa đỏ quỳ) và HClO (tính tẩy màu cực mạnh làm nhạt ngay màu đỏ).', difficulty: 'hard' },
  { id: 'qpkr_5', subjectId: 'pkr', content: 'Phosphorus đỏ cháy mãnh liệt sinh ra chất gì tạo khói mù?', type: 'multiple-choice', options: ['Khói trắng P2O5', 'Khí SO2', 'Khí rắn PCl3', 'Sương mù H2S'], correctAnswer: 'Khói trắng P2O5', explanation: '4P + 5O2 -> 2P2O5 là những hạt bột màu trắng li ti như sương mù.', difficulty: 'medium' },
  { id: 'qpkr_6', subjectId: 'pkr', content: 'Carbon có những tính chất hóa học nổi bật nào?', type: 'multiple-choice', options: ['Tính khử và oxi hóa', 'Chỉ tính khử', 'Chỉ tính oxi hóa', 'Không có tính oxi hóa hay khử'], correctAnswer: 'Tính khử và oxi hóa', explanation: 'C vừa thể hiện tính khử (nhường e cho O2) và oxi hóa (nhận e từ H2).', difficulty: 'hard' },
  { id: 'qpkr_7', subjectId: 'pkr', content: 'Chất khí nào được dùng để khử trùng nước sinh hoạt?', type: 'multiple-choice', options: ['O2', 'CO2', 'Cl2', 'N2'], correctAnswer: 'Cl2', explanation: 'Chlorine (Clo) có tính sát trùng mạnh nên được dùng để khử trùng nước.', difficulty: 'easy' },

  // --- HỢP CHẤT HỮU CƠ (hc) ---
  { id: 'qhc_1', subjectId: 'hc', content: 'Công thức phân tử của khí biogas Methane là gì?', type: 'multiple-choice', options: ['CH₄', 'C₂H₄', 'C₂H₂', 'C₆H₆'], correctAnswer: 'CH₄', explanation: 'Methane có công thức hóa học là CH₄, là thành phần chính của khí thiên nhiên và khí sinh học.', difficulty: 'easy' },
  { id: 'qhc_2', subjectId: 'hc', content: 'Nhóm chức đặc trưng trên thân cồn (Ethanol) là gì?', type: 'multiple-choice', options: ['-COOH', '-OH', '-NH2', '-CHO'], correctAnswer: '-OH', explanation: 'Ethanol (C2H5OH) có nhóm Hydroxyl (-OH).', difficulty: 'easy' },
  { id: 'qhc_3', subjectId: 'hc', content: 'Loại hydrocarbon nào làm phai nhạt màu da cam dung dịch Brom?', type: 'multiple-choice', options: ['Methane', 'Ethane', 'Ethylene', 'Tất cả các chất'], correctAnswer: 'Ethylene', explanation: 'C2H4 có liên kết đôi mỏng manh, sễ bị đứt và tham gia phản ứng cộng dung dịch Brom làm phai màu.', difficulty: 'medium' },
  { id: 'qhc_4', subjectId: 'hc', content: 'Phản ứng đặc trưng nhất của dòng họ Alkane (như CH4) là gì?', type: 'multiple-choice', options: ['Phản ứng cộng', 'Phản ứng thế', 'Phản ứng trùng hợp', 'Xà phòng hóa'], correctAnswer: 'Phản ứng thế', explanation: 'Do chỉ chứa các liên kết đơn C-C, C-H nên phản ứng đặc trưng là thế như tác dụng Clo ánh sáng.', difficulty: 'medium' },
  { id: 'qhc_5', subjectId: 'hc', content: 'Hồ tinh bột tác dụng được với chất nào sinh ra chất xanh tím?', type: 'multiple-choice', options: ['Quỳ tím', 'Dung dịch Brom', 'Nước Iốt (I2)', 'NaCl'], correctAnswer: 'Nước Iốt (I2)', explanation: 'Tinh bột gặp nước iốt sẽ cuộn lại tạo ra phức chất màu xanh tím.', difficulty: 'medium' },
  { id: 'qhc_6', subjectId: 'hc', content: 'Cách duy nhất nhận biết Glucozơ qua thuốc thử là gì?', type: 'multiple-choice', options: ['Cộng dd Brom', 'Thuốc thử AgNO3/NH3', 'Nước vôi trong', 'Hồ tinh bột'], correctAnswer: 'Thuốc thử AgNO3/NH3', explanation: 'Glucozơ tác dụng tráng bạc mạnh sinh ra lớp gương đẹp.', difficulty: 'medium' },
  { id: 'qhc_7', subjectId: 'hc', content: 'Ester là sản phẩm của phản ứng đun nóng của 2 loại chất nào?', type: 'multiple-choice', options: ['Acid và Base', 'Acid hữu cơ và Rượu', 'Kim loại và Nước', 'Phản ứng thủy phân'], correctAnswer: 'Acid hữu cơ và Rượu', explanation: 'Phản ứng este hóa từ CH3COOH và C2H5OH (có H2SO4 đặc làm xúc tác).', difficulty: 'hard' },
  { id: 'qhc_8', subjectId: 'hc', content: 'Đường kính Saccarozơ bị thủy phân sẽ ra 2 loại đường đơn nào?', type: 'multiple-choice', options: ['2 Fructozơ', '2 Glucozơ', 'Nước và Cacbon', 'Glucozơ và Fructozơ'], correctAnswer: 'Glucozơ và Fructozơ', explanation: 'Nó phân cắt làm đôi tạo thành hai phân tử đường mạch thẳng nhỏ là Glucozơ (nho) và Fructozơ (mật ong).', difficulty: 'hard' },
  { id: 'qhc_9', subjectId: 'hc', content: 'Phản ứng trùng hợp Ethylene tạo ra chất poly nào?', type: 'multiple-choice', options: ['PVC', 'PE', 'PP', 'Teflon'], correctAnswer: 'PE', explanation: 'nCH2=CH2 -> (-CH2-CH2-)n (Polyethylene).', difficulty: 'medium' },
  { id: 'qhc_10', subjectId: 'hc', content: 'Công thức hóa học của Acetic acid (Acid axetic) là gì?', type: 'multiple-choice', options: ['CH3OH', 'HCHO', 'CH3COOH', 'C2H5OH'], correctAnswer: 'CH3COOH', explanation: 'CH3COOH là thành phần chính của giấm ăn.', difficulty: 'easy' },
  { id: 'qhc_11', subjectId: 'hc', content: 'Độ rượu là gì?', type: 'multiple-choice', options: ['Số ml rượu nguyên chất trong 100ml hỗn hợp rượu và nước', 'Số gam rượu trong 100g nước', 'Khối lượng riêng của rượu', 'Nồng độ phần trăm của rượu'], correctAnswer: 'Số ml rượu nguyên chất trong 100ml hỗn hợp rượu và nước', explanation: 'Độ rượu = (V rượu / V hỗn hợp) * 100.', difficulty: 'medium' },
  { id: 'qhc_12', subjectId: 'hc', content: 'Chất béo là hỗn hợp nhiều ester của rượu nào?', type: 'multiple-choice', options: ['Methanol', 'Ethanol', 'Glycerol (Glixerol)', 'Ethylene glycol'], correctAnswer: 'Glycerol (Glixerol)', explanation: 'Chất béo (lipid) là triester của glycerol với các acid béo.', difficulty: 'hard' },
  { id: 'qhc_13', subjectId: 'hc', content: 'Protein bị thủy phân dưới tác dụng của men hoặc acid sinh ra chất gì?', type: 'multiple-choice', options: ['Các amino acid', 'Glucozơ', 'Acid béo', 'Saccarozơ'], correctAnswer: 'Các amino acid', explanation: 'Protein là các polymer được cấu tạo từ các mắt xích amino acid.', difficulty: 'hard' }
];

export const BADGES: Badge[] = [
  { id: 'b1', name: 'Nhà Hóa Học Nhí', icon: 'Award', description: 'Hoàn thành bài học đầu tiên.' },
  { id: 'b2', name: 'Bậc Thầy Nguyên Tử', icon: 'Zap', description: 'Đạt điểm tuyệt đối chủ đề Nguyên tử.' },
  { id: 'b3', name: 'Chiến Binh Hữu Cơ', icon: 'Flame', description: 'Vượt qua cấp độ Hợp chất hữu cơ.' },
  { id: 'b4', name: 'Chuỗi Chiến Thắng', icon: 'TrendingUp', description: 'Duy trì chuỗi học tập 7 ngày.' },
];

export const GEMINI_MODELS = [
  { id: 'gemini-3-flash-preview', name: 'Gemini 3 Flash (Nhanh)' },
  { id: 'gemini-3-pro-preview', name: 'Gemini 3 Pro (Thông minh)' },
  { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash' },
];
